/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard.properties'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveSlugRouteImport } from './routes/live.$slug'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/live/$slug',
  path: '/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/live/$slug': typeof LiveSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/live/': typeof LiveIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/live/$slug': typeof LiveSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/businesses': typeof BusinessesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/live': typeof LiveIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/live/$slug': typeof LiveSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/live/': typeof LiveIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/saved'
    | '/signup'
    | '/businesses/$slug'
    | '/dashboard/billing'
    | '/dashboard/business'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/services'
    | '/live/$slug'
    | '/properties/$slug'
    | '/businesses/'
    | '/dashboard/'
    | '/live/'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/marketplace'
    | '/saved'
    | '/signup'
    | '/businesses/$slug'
    | '/dashboard/billing'
    | '/dashboard/business'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/services'
    | '/live/$slug'
    | '/properties/$slug'
    | '/businesses'
    | '/dashboard'
    | '/live'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/saved'
    | '/signup'
    | '/businesses/$slug'
    | '/dashboard/billing'
    | '/dashboard/business'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/services'
    | '/live/$slug'
    | '/properties/$slug'
    | '/businesses/'
    | '/dashboard/'
    | '/live/'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  LiveSlugRoute: typeof LiveSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/live/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPropertiesRoute: DashboardPropertiesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  LiveSlugRoute: LiveSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
